In [2]:
import numpy as np
import torch

In [16]:
def reconstruct_operator(w, v):
    """
    Recreate a matrix from its eigenvalues and eigenvectors.
    """
    R = np.linalg.inv(v)
    # create diagonal matrix from eigenvalues
    L = np.diag(w)
    # reconstruct the original matrix
    B = v.dot(L).dot(R)
    return B

In [22]:
def eigen_init_(n_units, std=1):
    sampler = torch.distributions.Normal(torch.Tensor([0]), torch.Tensor([std/n_units]))
    Omega = sampler.sample((n_units, n_units))[..., 0]  
    w, v = np.linalg.eig(Omega.cpu().detach().numpy())
    w =np.random.uniform(-2,2, w.shape[0])
    return reconstruct_operator(w,v)

In [23]:
np.linalg.eig(eigen_init_(5,1))

[-0.63836712  1.27272341 -1.96890697 -1.82173631  1.66471135]
[[ 0.55234   +0.j          0.7566906 +0.j          0.7566906 -0.j
  -0.41695145+0.j         -0.17405729+0.j        ]
 [-0.3922205 +0.j          0.1996129 +0.17983553j  0.1996129 -0.17983553j
  -0.66501135+0.j         -0.3196221 +0.j        ]
 [ 0.12971687+0.j         -0.08042279-0.10640565j -0.08042279+0.10640565j
   0.42012116+0.j         -0.844013  +0.j        ]
 [-0.0601375 +0.j         -0.40667504-0.343105j   -0.40667504+0.343105j
   0.37898752+0.j          0.34135628+0.j        ]
 [-0.72155434+0.j          0.2057317 -0.10959933j  0.2057317 +0.10959933j
   0.2525432 +0.j         -0.19663097+0.j        ]]


(array([-1.96890699-1.29908270e-08j, -1.82173625-4.59137936e-15j,
        -0.63836711-4.21455068e-16j,  1.27272342-8.39741879e-09j,
         1.66471139+2.29606237e-16j]),
 array([[ 0.75669068+0.00000000e+00j,  0.41695149-1.02486236e-07j,
         -0.55233995-1.09789306e-08j,  0.75669063+0.00000000e+00j,
          0.17405729-2.97513723e-08j],
        [ 0.19961283-1.79835454e-01j,  0.66501134+0.00000000e+00j,
          0.3922205 -2.94885593e-09j,  0.19961291+1.79835533e-01j,
          0.31962211-1.13231523e-08j],
        [-0.08042274+1.06405593e-01j, -0.42012116-8.12922651e-09j,
         -0.12971687+1.51768766e-09j, -0.08042279-1.06405644e-01j,
          0.84401298+0.00000000e+00j],
        [-0.40667502+3.43105008e-01j, -0.37898749+6.11834306e-08j,
          0.0601375 +7.94463760e-09j, -0.40667505-3.43104990e-01j,
         -0.34135629+2.12215151e-08j],
        [ 0.20573177+1.09599277e-01j, -0.25254318-4.61054146e-08j,
          0.72155434+0.00000000e+00j,  0.2057317 -1.09599333e-01j,
   