In [1]:
import xarray
import numpy as np
import sys

In [2]:
import scipy
np.set_printoptions(threshold=sys.maxsize)

In [3]:
def subsample(data, sample_size):
    samples = list(zip(*[iter(data)]*sample_size))   # use 3 for triplets, etc.
    return map(lambda x:sum(x)/float(len(x)), samples)

In [10]:
!ls /g/data/x77/ob2720/partition/train/1999*.nc

/g/data/x77/ob2720/partition/train/1999003N05114.nc
/g/data/x77/ob2720/partition/train/1999013S13164.nc
/g/data/x77/ob2720/partition/train/1999015S20036.nc
/g/data/x77/ob2720/partition/train/1999020S17158.nc
/g/data/x77/ob2720/partition/train/1999021S13113.nc
/g/data/x77/ob2720/partition/train/1999021S15149.nc
/g/data/x77/ob2720/partition/train/1999024S11138.nc
/g/data/x77/ob2720/partition/train/1999029S14096.nc
/g/data/x77/ob2720/partition/train/1999031N08092.nc
/g/data/x77/ob2720/partition/train/1999033S14118.nc
/g/data/x77/ob2720/partition/train/1999040S13160.nc
/g/data/x77/ob2720/partition/train/1999040S15147.nc
/g/data/x77/ob2720/partition/train/1999043S18038.nc
/g/data/x77/ob2720/partition/train/1999045N11138.nc
/g/data/x77/ob2720/partition/train/1999048S21152.nc
/g/data/x77/ob2720/partition/train/1999056S20035.nc
/g/data/x77/ob2720/partition/train/1999057S22203.nc
/g/data/x77/ob2720/partition/train/1999060S10089.nc
/g/data/x77/ob2720/partition/train/1999070S19206.nc
/g/data/x77/

In [23]:
cyclone_ds = xarray.open_dataset("/g/data/x77/ob2720/partition/train/1999013S13164.nc", \
                                         engine='netcdf4', cache=True, chunks='auto', decode_cf=False)
cyclone_ds

<xarray.Dataset>
Dimensions:  (level: 5, time: 135, latitude: 160, longitude: 160)
Coordinates:
  * level    (level) int32 225 500 650 750 850
  * time     (time) int64 0 3 6 9 12 15 18 21 ... 384 387 390 393 396 399 402
Dimensions without coordinates: latitude, longitude
Data variables:
    u        (time, level, latitude, longitude) int16 dask.array<chunksize=(135, 5, 160, 160), meta=np.ndarray>
    v        (time, level, latitude, longitude) int16 dask.array<chunksize=(135, 5, 160, 160), meta=np.ndarray>
    z        (time, level, latitude, longitude) int16 dask.array<chunksize=(135, 5, 160, 160), meta=np.ndarray>
    pv       (time, level, latitude, longitude) int16 dask.array<chunksize=(135, 5, 160, 160), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2020-10-23 15:55:33 UTC+1100 by era5_replication_tools-1.2....
    license:      Licence to use Copernicus Products: https://apps.ecmwf.int/...
    summary:      ERA5 is the fifth generation ECMWF atmospheric reanalysis o...
    title:        ERA5 pressure-levels oper u_component_of_wind 19990101-1999...

In [43]:
cyclone_ds = xarray.open_dataset("/g/data/x77/ob2720/partition/train/1999031N08092.nc", \
                                         engine='netcdf4', cache=True, chunks='auto', decode_cf=False)
cyclone_ds = cyclone_ds[dict(time=list(range(0, 8)),level=[1])][['v']]
cyclone_array = cyclone_ds.to_array().to_numpy()
cyclone_array = cyclone_array[:,:,:,40:120,40:120]
cyclone_array_new = cyclone_array[:,:,:,::4,::4].copy()
cyclone_array = cyclone_array.transpose((1,0,2,3,4))
cyclone_array_new = cyclone_array_new.transpose((1,0,2,3,4))
cyclone_array = cyclone_array.reshape((8,-1,80,80))
cyclone_array_new = cyclone_array_new.reshape((8,-1,20,20))
# print(cyclone_array[0])
print(cyclone_array_new[0])

[[[4909 4482 4468 4453 4510 4428 4497 4648 4295 3846 3498 3317 3237 3159
   3108 3241 3283 3331 3818 3795]
  [4384 4465 4410 4345 4307 4348 4372 4083 3748 3449 3252 3106 3020 2947
   2872 2892 3180 3443 3508 3935]
  [4438 4202 4084 4068 3994 3897 3765 3465 3182 3027 2864 2773 2668 2650
   2665 2754 2925 3335 4063 4486]
  [3986 3938 3907 3665 3472 3402 3172 2900 2724 2677 2614 2504 2543 2666
   2796 2766 3037 4006 4302 4431]
  [4082 3989 3612 3368 3285 3072 2885 2815 3077 2984 2801 2672 2862 2904
   3116 3333 3868 4258 4548 4856]
  [4021 3565 3281 3251 3107 2940 2866 2950 2880 2865 2972 3281 3595 3703
   3909 3930 4106 4555 4817 5048]
  [3623 3402 3253 2987 2807 2793 2526 3290 3100 3415 3726 4075 4207 4292
   4448 4567 4223 4201 4713 4978]
  [3353 3112 2962 2708 2283 2128 2530 4200 4429 4410 4395 4538 4667 4845
   5066 4951 5079 4928 4708 4846]
  [3063 3014 2796 2491 2530 2258 2852 4539 5281 5350 5150 5142 5068 5381
   5585 5586 5497 5142 4673 5517]
  [3023 3045 3132 3508 3639 3425 4469

In [31]:
array = np.load("/g/data/x77/jm0124/np_cyclones_crop/4/train/1979066S15124-41.npy")
print(array[0])

[[[  5.7529364    6.599325     7.1140566    8.045349     9.507294
    10.656153    11.168232    11.35396     11.988088    11.839505
    10.470425     8.928884     8.644985     6.8805704    6.1429653
     5.951931     4.407736     5.2514706    2.6592398    2.9139528 ]
  [  4.869402     5.28331      5.8988657    6.594018     7.703079
     9.019094     9.923855    10.5818615   10.979851    11.279669
    11.213337    10.33511     10.024678     9.212782     7.9577923
     6.6550436    5.4823046    5.601701     4.023013     3.8027935 ]
  [  3.2243834    3.8930044    4.800418     5.6866045    6.9920073
     7.9843245    8.557427     8.968682     9.082772     9.857523
    11.473356    10.799429    10.117542     9.133184     8.236383
     8.050656     6.575445     4.7234735    3.3225536    3.8452454 ]
  [  2.9378319    3.7417688    4.203435     4.6969404    5.216979
     5.2328978    5.198406     5.2912703    5.0392103    6.201337
     8.03739     10.000799    10.579208    10.221019     8.46721

In [6]:
import seaborn
seaborn.heatmap(array[1,0,:,:]/1000)

ModuleNotFoundError: No module named 'seaborn'

In [4]:
!ls /g/data/x77/jm0124/np_cyclones_crop/2/train

1979066S15124-10.npy   1989150N09257-46.npy   2004074N03143-26.npy
1979066S15124-11.npy   1989150N09257-47.npy   2004074N03143-27.npy
1979066S15124-12.npy   1989150N09257-48.npy   2004074N03143-28.npy
1979066S15124-13.npy   1989150N09257-49.npy   2004074N03143-29.npy
1979066S15124-14.npy   1989150N09257-5.npy    2004074N03143-3.npy
1979066S15124-15.npy   1989150N09257-50.npy   2004074N03143-30.npy
1979066S15124-16.npy   1989150N09257-51.npy   2004074N03143-31.npy
1979066S15124-17.npy   1989150N09257-52.npy   2004074N03143-32.npy
1979066S15124-18.npy   1989150N09257-53.npy   2004074N03143-33.npy
1979066S15124-19.npy   1989150N09257-54.npy   2004074N03143-34.npy
1979066S15124-2.npy    1989150N09257-6.npy    2004074N03143-35.npy
1979066S15124-20.npy   1989150N09257-7.npy    2004074N03143-36.npy
1979066S15124-21.npy   1989150N09257-8.npy    2004074N03143-37.npy
1979066S15124-22.npy   1989150N09257-9.npy    2004074N03143-38.npy
1979066S15124-23.npy   1989209N22130-10.npy   2004074N03143-39.

In [30]:
print(array[::-1][0])
print(array[-1])

[[[-12923 -12934 -12936 ... -11476 -11704 -11749]
  [-12860 -12848 -12871 ... -11508 -11645 -11627]
  [-12688 -12690 -12743 ... -11484 -11512 -11445]
  ...
  [  8997   8750   8559 ...   -651   -590   -524]
  [  7854   7661   7546 ...   -680   -605   -530]
  [  6682   6593   6555 ...   -685   -588   -501]]]
[[[-12923 -12934 -12936 ... -11476 -11704 -11749]
  [-12860 -12848 -12871 ... -11508 -11645 -11627]
  [-12688 -12690 -12743 ... -11484 -11512 -11445]
  ...
  [  8997   8750   8559 ...   -651   -590   -524]
  [  7854   7661   7546 ...   -680   -605   -530]
  [  6682   6593   6555 ...   -685   -588   -501]]]


In [5]:
from datasets import *

ModuleNotFoundError: No module named 'torch'

In [1]:
!ls /g/data/x77/ob2720/partition/train/

1979002S04179.nc  1988304S08077.nc  1999021S13113.nc  2009288N07267.nc
1979002S16147.nc  1988307N09131.nc  1999021S15149.nc  2009299N12153.nc
1979003S10052.nc  1988308N09140.nc  1999024S11138.nc  2009305N14134.nc
1979008S14137.nc  1988310S08100.nc  1999029S14096.nc  2009325N06148.nc
1979027S15167.nc  1988319N08090.nc  1999031N08092.nc  2010029S12177.nc
1979031S12056.nc  1988323N15286.nc  1999033S14118.nc  2010084S09138.nc
1979035S19042.nc  1988327N06100.nc  1999040S13160.nc  2010151N14065.nc
1979041S19041.nc  1988347S12128.nc  1999040S15147.nc  2010176N16278.nc
1979041S19051.nc  1988352S14166.nc  1999043S18038.nc  2010234N11329.nc
1979042S05170.nc  1988356N05142.nc  1999045N11138.nc  2010236N12341.nc
1979043S11161.nc  1988364S17148.nc  1999048S21152.nc  2010240N15142.nc
1979051S16187.nc  1989002S14192.nc  1999056S20035.nc  2010241N25125.nc
1979066S13068.nc  1989006S13184.nc  1999057S22203.nc  2010242N14318.nc
1979066S15124.nc  1989010N16212.nc  1999060S10089.nc  2010243N12146.nc
197906